# Generated by Django 4.0.2 on 2022-03-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(default='', max_length=100)),
                ('Brand', models.CharField(default='', max_length=100)),
                ('Quantity', models.PositiveIntegerField()),
                ('Value', models.CharField(default='', max_length=100)),
                ('Unit_Price', models.PositiveIntegerField()),
                ('Total_Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
            ],
        ),
    ]
