# Generated by Django 4.0.2 on 2022-02-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=100)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=16)),
                ('Value', models.CharField(max_length=100)),
                ('Unit_Price', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
    ]
