# Generated by Django 4.0.2 on 2022-02-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Total_Price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=16),
        ),
    ]
