# Generated by Django 4.0.2 on 2022-02-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Total_Price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
