# Generated by Django 4.0.2 on 2022-02-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Unit_Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
