# Generated by Django 4.0.2 on 2022-02-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_quantity_alter_invoice_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Total_Price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Unit_Price',
        ),
    ]
