# Generated by Django 4.0.2 on 2022-02-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_invoice_quantity_remove_invoice_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Total_Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Unit_Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
