# Generated by Django 4.0.2 on 2022-03-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_quantity_invoice_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Total_Price',
        ),
    ]
